# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Individual',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('surname', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('code', models.CharField(max_length=7)),
            ],
        ),
        migrations.AddField(
            model_name='individual',
            name='school',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='tournament.School'),
        ),
    ]
